version: '3'

services:
  app:
    build: .
    ports:
      - "8765:8765"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
